/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template

 */
package universityscdproject;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.awt.GridLayout;
import java.awt.BorderLayout;
import java.awt.Image;
import java.awt.Color;
import java.awt.Font;
import javax.swing.JPanel;
import javax.swing.JLabel;
import javax.swing.ImageIcon;
import javax.swing.JButton; 
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;

 


/**
 *
 * @author haide
 */
public class Home extends javax.swing.JFrame {
    
    private String loggedInUserEmail = ""; 

    public void setLoggedInEmail(String email) {
        this.loggedInUserEmail = email;
    }
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Home.class.getName());
    
    

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        loadCars();
   
}
 
 
 
public void loadCars() {
    JPanel container = new JPanel(new java.awt.GridLayout(0, 3, 20, 20)); 
    container.setBackground(java.awt.Color.WHITE);
    container.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));

    JPanel wrapper = new JPanel(new java.awt.BorderLayout());
    wrapper.setBackground(java.awt.Color.WHITE);
    wrapper.add(container, java.awt.BorderLayout.NORTH); 

    try (java.sql.Connection con = java.sql.DriverManager.getConnection("jdbc:mysql://localhost:3306/car_rental_db", "root", "");
         java.sql.ResultSet rs = con.createStatement().executeQuery("SELECT * FROM cars")) {
        
        while(rs.next()) {
            JPanel carCard = new JPanel(new java.awt.BorderLayout(0, 10)); 
            carCard.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(230, 230, 230), 1));
            carCard.setBackground(java.awt.Color.WHITE);
            
             javax.swing.JLabel imgLbl = new javax.swing.JLabel();
            String path = rs.getString("image_path");
            try {
                javax.swing.ImageIcon icon = new javax.swing.ImageIcon(path);
                java.awt.Image img = icon.getImage().getScaledInstance(465, 180, java.awt.Image.SCALE_SMOOTH);
                imgLbl.setIcon(new javax.swing.ImageIcon(img));
            } catch (Exception e) { 
                imgLbl.setText("No Image Found"); 
                imgLbl.setHorizontalAlignment(javax.swing.JLabel.CENTER);
            }
            carCard.add(imgLbl, java.awt.BorderLayout.NORTH); 

             JPanel infoPanel = new JPanel(new java.awt.GridLayout(0, 1, 5, 5));
            infoPanel.setBackground(java.awt.Color.WHITE);
            infoPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 10, 5, 10));
            infoPanel.add(new javax.swing.JLabel("Brand: " + rs.getString("brand") + " | Model: " + rs.getString("model")));

            javax.swing.JTextArea descArea = new javax.swing.JTextArea(rs.getString("description"));
            descArea.setLineWrap(true);
            descArea.setEditable(false);
            infoPanel.add(descArea);
            carCard.add(infoPanel, java.awt.BorderLayout.CENTER);

             // Your screenshot image_6ba8bf.jpg shows the column is named "id"
            final int actualId = rs.getInt("id"); 
            String price = rs.getString("price_per_day");

            javax.swing.JButton rentBtn = new javax.swing.JButton("Book Now: Rs. " + price + " Per Day");
            rentBtn.setBackground(new java.awt.Color(102, 255, 204));
            
            rentBtn.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    // This passes the ID to the constructor
                    orderdetails orderPage = new orderdetails(actualId); 
                    orderPage.setVisible(true);
                    orderPage.pack();
                    orderPage.setLocationRelativeTo(null);
                }
            });

            carCard.add(rentBtn, java.awt.BorderLayout.SOUTH); 
            container.add(carCard);
        }
        jScrollPane1.setViewportView(wrapper);
    } catch (Exception e) {
        e.printStackTrace();
    }
}
            
         
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        user = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        LogoutBtn = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();

        jMenuItem1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenuItem1.setText("Change Password");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItem1);

        jMenuItem2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenuItem2.setText("LogOut");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItem2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setMaximumSize(new java.awt.Dimension(32767, 80));
        jPanel1.setPreferredSize(new java.awt.Dimension(1107, 80));

        user.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        user.setForeground(new java.awt.Color(0, 51, 102));
        user.setText("Haider ");
        user.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        user.setRequestFocusEnabled(false);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 51));
        jLabel1.setText("Welcome |");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel2.setText("| Cars available in Lahore only");

        LogoutBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LogoutBtn.setText("Setting");
        LogoutBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogoutBtnMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                LogoutBtnMouseReleased(evt);
            }
        });
        LogoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutBtnActionPerformed(evt);
            }
        });

        jButton1.setText("My Booking");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Update Booking");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Cancel Booking");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Contact Us");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Return Car");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(user)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(141, 141, 141)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 115, Short.MAX_VALUE)
                .addComponent(LogoutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(user, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LogoutBtn)
                    .addComponent(jButton4)
                    .addComponent(jButton5))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.NORTH);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1381, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 508, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(jPanel2);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LogoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutBtnActionPerformed

    }//GEN-LAST:event_LogoutBtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
 
    if (loggedInUserEmail == null || loggedInUserEmail.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Error: User email not found. Please log in again.");
        return;
    }

     Bookingdetails detailsPage = new Bookingdetails(loggedInUserEmail);
    detailsPage.setVisible(true);
    detailsPage.setLocationRelativeTo(null);
    
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
        canceldetails cancelPage = new canceldetails(); 
    
     cancelPage.setVisible(true);
 
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
  
    updatedetail updatePage = new updatedetail(); 
    
     updatePage.setVisible(true);
    
 
    }//GEN-LAST:event_jButton2ActionPerformed

    private void LogoutBtnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutBtnMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_LogoutBtnMouseReleased

    private void LogoutBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutBtnMouseClicked
        // TODO add your handling code here:
        
     // Check if the left mouse button was clicked
    if (javax.swing.SwingUtilities.isLeftMouseButton(evt)) {
        // Show the menu directly below the button/label
        jPopupMenu1.show(evt.getComponent(), 0, evt.getComponent().getHeight());
    }

    }//GEN-LAST:event_LogoutBtnMouseClicked

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
         Login LoginFrame = new Login();
        LoginFrame.setVisible(true);
        LoginFrame.pack();
        LoginFrame.setLocationRelativeTo(null);
     this.dispose();
        
        
        
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
     ChangePassword cp = new ChangePassword();
    cp.setVisible(true);
    cp.pack();
    cp.setLocationRelativeTo(null);         
       
        
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    Contactdetails contactPage = new Contactdetails();
    contactPage.setVisible(true);
    contactPage.pack();
    contactPage.setLocationRelativeTo(null); 
 
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        
     Returndetail returnFrame = new Returndetail();
    returnFrame.setVisible(true);
    returnFrame.pack();
    returnFrame.setLocationRelativeTo(null);

    }//GEN-LAST:event_jButton5ActionPerformed

    public void setUser(String name){
        user.setText(name);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LogoutBtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel user;
    // End of variables declaration//GEN-END:variables
}
