/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package universityscdproject;

import java.awt.GridBagLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author haide
 */


public class PanelAction extends javax.swing.JPanel {

    public PanelAction() {
        initComponents();
         this.setLayout(new java.awt.GridBagLayout());
        
         this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 5, 0, 0));
    }

    public void initEvent(TableActionEvent event, int row) {
         jButton1.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                event.onDelete(row);
            }
        });
    
    
         jButton2.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                event.onApprove(row); // This calls the new method we added to the interface
            }
        });

         jButton3.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                event.onReject(row); 
            }
        });
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setLayout(new java.awt.GridBagLayout());

        jButton1.setText("Delete");
        add(jButton1, new java.awt.GridBagConstraints());

        jButton2.setText("Accept");
        add(jButton2, new java.awt.GridBagConstraints());

        jButton3.setText("Reject");
        add(jButton3, new java.awt.GridBagConstraints());
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButton1;
    public javax.swing.JButton jButton2;
    public javax.swing.JButton jButton3;
    // End of variables declaration//GEN-END:variables
}
